export { default as Login } from './login/login'
export { default as FormularioChamados } from './formularioChamados/formularioChamados'
export { default as HomeSolicitantes } from './home-solicitantes/home-solicitantes'
export { default as Chamados } from './chamados/chamados'
export { default as CadastroUsuarios } from './usuarios/cadastro/cadastroUsuarios'
export { default as CadastroEquipe } from './equipe/cadastroEquipe'