export { default as Login } from './login/login'
export { default as FormularioChamados } from './formularioChamados/formularioChamados'
export { default as HomeSolicitantes } from './home-solicitantes/home-solicitantes'
export { default as Chamados } from './chamados/chamados'
export { default as CadastroUsuarios } from './usuarios/cadastro/cadastro-usuarios'
export { default as ListagemUsuarios } from './usuarios/listagem/listagem-usuarios'
export { default as EdicaoUsuarios } from './usuarios/edicao/edicao-usuarios'
